---
- name: Ansible Copy Directory Example Local to Remote
  hosts: STAG
  tasks:
    - name: sync
      synchronize:
        src: ../custom_addons/
        dest: STAG-custom-addons
        delete: yes
        recursive: yes

    # - name: restart ${{target}}
    #   command: echo ${{target}} passed