name: gulffruits PROD

on:
  push:
    branches:
      - PROD
  # pull_request:

jobs:
  deploy_staging:
    runs-on: self-hosted
    name: Run Ansible Playbook

    steps:
      - uses: actions/checkout@v3
      - name: Execute Ansible Playbook
        uses: ./
      - run: cd ansible && ansible-playbook -i inventry.txt -e PROD PROD-deploy.yml
        shell: bash