name: gulffruits STAG

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy_staging:
    runs-on: self-hosted
    name: Run Ansible Playbook

    steps:
      - uses: actions/checkout@v3
      - name: Execute Ansible Playbook
        uses: ./
        env:
          target: STAG
      - run: cd ansible
        shell: bash
      - run: ansible-playbook -i inventry.txt -e $target deploy.yml
        shell: bash
